apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "charts.name" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "charts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "charts.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.healthCheckPath }}
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.healthCheckPath }}
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            {{- if .Values.deployment.configMap }}
            - configMapRef:
                name: {{ .Values.deployment.configMap }}
            {{- end }}
            {{- if .Values.deployment.secret }}
            - secretRef:
                name: {{ .Values.deployment.secret }}
            {{- end }}
