# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "devops"
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with 'github-actions'
      prefix: "github-actions"

  - package-ecosystem: "docker"
    directory: "/"
    ignore:
      - dependency-name: node
      - dependency-name: ruby
      - dependency-name: dotnet/sdk
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "dependencies"
      - "devops"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with 'docker'
      prefix: "docker"

  - package-ecosystem: "npm" # for yarn
    directory: "/" # Look for `package.json` and `lock` files in the `root` directory
    schedule:
      interval: "monthly"
      day: "monday"
    labels:
      - "front-end"
      - "dependencies"
    versioning-strategy: increase
    commit-message:
      # Prefix all commit messages with 'npm'
      prefix: "npm"
    # Create a group of dependencies to be updated together in one pull request
    groups:
      # Specify a name for the group, which will be used in pull request titles
      # and branch names. The first matching group is used.
      react:
        patterns:
          - "react"
          - "react-dom"
          - "react-test-renderer"
      next:
        patterns:
          - "next"
          - '@next*'
          - "eslint-config-next" # excluded in linters-and-formatters group
      storybook:
        patterns:
          - "chromatic"
          - "storybook"
          - "@storybook*"
          - "eslint-plugin-storybook" # excluded in linters-and-formatters group
      sentry:
        patterns:
          - "@sentry*"
      linters-and-formatters:
        patterns:
          - "*eslint*"
          - "*prettier*"
          - "*stylelint*"
        exclude-patterns:
          - eslint-config-next
          - eslint-plugin-storybook
      testing:
        patterns:
          - "*jest*"
          - "*playwright*"
          - "*testing-library*"
          - "*size-limit*"
      dependencies-minor:
        # Open a PR with all minor version updates from "dependencies" in package.json
        dependency-type: "production"
        update-types:
        - "minor"
      dependencies-patch:
        # Open a PR with all patch version updates from "dependencies" in package.json
        dependency-type: "production"
        update-types:
        - "patch"
      devDependencies:
        # Open a PR with all updates from "devDependencies" in package.json
        dependency-type: "development"

  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    ignore:
      - dependency-name: nokogiri
        versions:
          - "> 1.12.0"
      - dependency-name: "*"
        update-types: ["version-update:semver-major","version-update:semver-minor"]
    labels:
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with 'bundler'
      prefix: "bundler"

  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "back-end"
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with 'nuget'
      prefix: "nuget"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "monthly"
      day: "monday"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    labels:
      - "back-end"
      - "dependencies"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with 'go'
      prefix: "go"
