# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: ".github/"
    schedule:
      interval: "weekly"
      day: "monday"
    labels:
      - "devops"
    reviewers:
      - "Andrews-McMeel-Universal/devops-engineers"
    open-pull-requests-limit: 10
    commit-message:
      # Prefix all commit messages with "github-actions"
      prefix: "github-actions"
