name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
  - title: 🚀 Features
    when:
      labels:
        - 'feature'
        - 'epic'
        - 'story'
  - title: 🐛 Fixes
    when:
      labels:
      - 'bug'
  - title: 🔨 Maintenance
    when:
      labels:
      - 'tools'
      - 'tests'
      - 'dependencies'
      - 'documentation'
  - type: 'pre-exclude'
    when:
      label: 'skip-changelog'
  - type: 'version-resolver'
    semver-increment: 'major'
    when:
      labels:
      - 'major'
      - 'epic'
      - 'feature'
  - type: 'version-resolver'
    semver-increment: 'minor'
    when:
      labels:
      - 'minor'
      - 'story'
      - 'maintenance'
      - 'research'
  - type: 'version-resolver'
    semver-increment: 'patch'
    when:
      labels:
      - 'patch'
      - 'bug'
      - 'sync'
  - type: 'version-resolver'
    semver-increment: 'patch'
change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&'
filter-by-commitish: true
commitish: main
exclude-contributors:
  - 'dependabot[bot]'
  - 'amutechtest'
  - 'github-actions'
autolabeler:
  - label: 'documentation'
    files:
      - '**/*.md'
  - label: 'dependencies'
    files:
      - '{yarn,Gemfile}.lock'
      - 'package*.json'
      - 'Gemfile'
      - '.ruby-{version,gemset}'
      - '**/*.csproj'
      - '**/pnpm-lock.yaml'
      - '.yarn/'
      - '.{npm,nvm}rc'
  - label: 'front-end'
    files:
      - '**/*.{js,js.html,jsx,ts,tsx,html,css,less,scss,sass,otf,eot,ttf,woff*,erb}'
      - 'public/'
      - 'src/'
      - 'wp-content/'
      - 'package.json'
      - '!/.vscode'
      - '!/.devcontainer'
      - '!**/*.test.js'
  - label: 'back-end'
    files:
      - '**/*.{cs,sln,csproj,ru}'
      - 'appsettings.*json'
      - 'CodeCoverage.runsettings'
  - label: 'tools'
    files:
      - '/.vscode'
      - '/.devcontainer'
      - 'stylelint.config.js'
      - '.{prettierrc,size-limit,eslintrc}.js'
      - '.{yarnrc,solargraph,postcssrc,erb-lint,rubocop}.yml'
      - '.{prettierrc,eslintrc,stylelintrc}.json'
      - 'playwright/**'
      - '.spec.*'
      - '*.test.js'
      - '{jest,playwright}.*.js'
      - '.storybook/'
      - '.browserlistrc'
  - label: 'devops'
    files:
      - '.github/'
      - 'deployments/'
      - '*.ps1'
      - 'Secrets-example.json'
      - 'docker-compose.yml'
      - 'Dockerfile'
include-pre-releases: true
template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION
