apiVersion: v1
kind: Service
metadata:
  name: {{ include "charts.name" . }}
  labels:
    {{- include "charts.labels" . | nindent 4 }}
{{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
{{- if (eq .Values.service.type "ClusterIP") }}
      nodePort: null
{{- end }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "charts.selectorLabels" . | nindent 4 }}
