name: Cache Yarn Install

description: 'Sets up the application based on our version, installs it, and then installs dependencies.  If no changes to these dependencies are detected, it will attempt to use the cached version.'

runs:
  using: 'composite'
  steps:
  # Installs node and caches the global yarn cache (does not cache node_modules)
  - name: Setup application platform
    uses: actions/setup-node@v3
    with:
      node-version-file: '.nvmrc'
      cache: 'yarn'

  # Caches node_modules, breaks cache when yarn.lock is updated
  - name: Cache dependencies
    id: dependency-cache
    uses: actions/cache@v3
    with:
      path: |
        ${{ github.workspace }}/node_modules
      key: ${{ runner.os }}-nextjs-install-${{ hashFiles('**/.env') }}-${{ hashFiles('yarn.lock') }}

  # Installs dependencies if the cache was broken
  - name: Install dependencies
    if: steps.dependency-cache.outputs.cache-hit != 'true'
    shell: sh
    run: yarn install --frozen-lockfile --prefer-offline
