name: Cache Ruby Install 

description: 'Sets up the application based on our version, installs it, and then installs dependencies.  If no changes to these dependencies are detected, it will attempt to use the cached version.'

runs:
  using: 'composite'
  steps:
  # Caches nuget packages, breaks cache when packages.lock.json is updated
  - name: Cache dependencies
    id: dependency-cache
    uses: actions/cache@v3
    with:
      path: |
        /bundler
      # Look to see if there is a cache hit for the corresponding requirements file
      key: ${{ runner.os }}-ruby-install-${{ hashFiles('**/*.lock') }}

  - name: Install necessary packages
    if: steps.dependency-cache.outputs.cache-hit != 'true'
    shell: sh
    run: |
      sudo apt-get update -y --fix-missing &&
      sudo apt-get install -y ${{ env.aptPackages }}

  # Installs Ruby Bundler packages
  - name: Set up Ruby
    if: steps.dependency-cache.outputs.cache-hit != 'true'
    uses: ruby/setup-ruby@v1.136.0
    with:
      ruby-version: ${{ env.rubyVersion }}
      bundler-cache: true