name: Use build cache

description: Builds the application and caches the result

runs:
  using: 'composite'
  steps:
  # Caches the app's build files, breaks cache when the packages.lock.json
  - name: Cache build
    id: build-cache
    uses: actions/cache@v3
    with:
      path: |
        ${{ github.workspace }}/.nuget/packages
      key: ${{ runner.os }}-dotnet-build-${{ hashFiles('**/packages.lock.json') }}

  # Builds the app if the cache was broken
  - name: Build app
    shell: sh
    if: steps.build-cache.outputs.cache-hit != 'true'
    run: dotnet build "${{ env.dotnetProjectFile }}" -c Release --no-restore