on:
  workflow_call:
    inputs:
      aks_cluster_name:
        required: true
        type: string
        description: "Azure Kubernetes cluster name."
      aks_cluster_rg:
        required: true
        type: string
        description: "Azure Kubernetes cluster resource group."
      environment:
        required: true
        type: string
        description: "Deploy environment. Can be development, staging, or production."
      charts_path:
        required: true
        type: string
        description: "Relative path to Helm charts."
      container_registry:
        required: true
        type: string
        description: "Azure Container Registry name."
      docker_image_name:
        required: true
        type: string
        description: "Name for docker image."
      docker_image_tag:
        required: true
        type: string
        description: "Name for docker image tag."
      dockerfile_path:
        required: true
        type: string
        description: "Relative path to Dockerfile."
      aks_ingress_fqdn:
        required: true
        type: string
        description: "FQDN for Azure Kubernetes Ingress."
      dns_rg:
        required: true
        type: string
        description: "Azure Resource Group for DNS Domain."
      application_maximum_replicas:
        required: false
        type: string
        description: "Maximum number of replicas for the application HPA."
        default: 4
      secret_key1:
        required: false
        type: string
        description: "Key for 1st Kubernetes Secret."
      secret_key2:
        required: false
        type: string
        description: "Key for 2nd Kubernetes Secret."
      secret_key3:
        required: false
        type: string
        description: "Key for 3rd Kubernetes Secret."
      secret_key4:
        required: false
        type: string
        description: "Key for 4th Kubernetes Secret."
      secret_key5:
        required: false
        type: string
        description: "Key for 5th Kubernetes Secret."
      secret_key6:
        required: false
        type: string
        description: "Key for 6th Kubernetes Secret."
      secret_key7:
        required: false
        type: string
        description: "Key for 7th Kubernetes Secret."
      secret_key8:
        required: false
        type: string
        description: "Key for 8th Kubernetes Secret."
    secrets:
      azure_credentials:
        required: true
      registry_username:
        required: true
      registry_password:
        required: true
      secret_value1:
        required: false
      secret_value2:
        required: false
      secret_value3:
        required: false
      secret_value4:
        required: false
      secret_value5:
        required: false
      secret_value6:
        required: false
      secret_value7:
        required: false
      secret_value8:
        required: false
         
      
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - id: getlatestrelease
        uses: thebritican/fetch-latest-release@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout if Staging or Development deployment.
        if: ${{ inputs.environment != 'production'}}
        uses: actions/checkout@master

      - name: Checkout Latest release if Production deployment.
        if: ${{ inputs.environment == 'production'}}
        uses: actions/checkout@v2
        with: 
          ref: ${{ steps.getlatestrelease.outputs.tag_name }}

      - name: Get Env
        id: getenvs
        shell: pwsh
        run: |
          function Get-Envs {
            param (
                  [parameter(Mandatory = $true, ValueFromPipeline = $true)]
                  [string]$PathToYaml
                  )

                  #Check to see if powershell-yaml is installed 
                  if (Get-Module -Name powershell-yaml) {
                    #It's installed, this would be if you are running locally. 
                  }
                  else {
                      Write-Host "Installing Powershell-Yaml."
                      Install-Module -Name powershell-yaml -Confirm:$false -Force
                  }

                  Import-Module powershell-yaml

                  Write-Host "Getting configuration from: $PathToYaml."

                  $Values = Get-Content $PathToYaml | ConvertFrom-Yaml

                  return $Values
          }

          $AppEnv = "${{ inputs.environment }}"
          $BasePath = Get-Location
          $YamlPath = Join-Path $BasePath ${{ inputs.charts_path }} "values.yaml"
          $AppConfig = Get-Envs -PathToYaml $YamlPath
          $YamlPath = Join-Path $BasePath ${{ inputs.charts_path }} "Chart.yaml"
          $ChartConfig = Get-Envs -PathToYaml $YamlPath
          $AppName = $ChartConfig.name
          $ConfigMap = $AppConfig.deployment.configMap
          $ConfigSecret = $AppConfig.deployment.secret
          $Ingress = $AppConfig.ingress.host
          $DomainName = ($Ingress.Split('.') | Select-Object -Last 2) -join '.'
          $HostName = $Ingress -replace $DomainName, ''
          $HostName = $HostName.Substring(0,$HostName.Length-1)
          switch ($AppEnv) {
            'development' {$HostName = "development.$Hostname"; $Ingress = "development.$Ingress"}
            'staging' {$HostName = "staging.$Hostname"; $Ingress = "staging.$Ingress"}
          }
          $ImagePullSecret = "$AppName-pull-secret"
          echo "::set-output name=APPNAME::$AppName"
          echo "::set-output name=CONFIGMAP::$ConfigMap"
          echo "::set-output name=CONFIGSECRET::$ConfigSecret"
          echo "::set-output name=APPINGRESS::$Ingress"
          echo "::set-output name=DOMAINNAME::$DomainName"
          echo "::set-output name=HOSTNAME::$HostName"
          echo "::set-output name=IMAGEPULLSECRET::$ImagePullSecret"

      - name: Login via Az module
        uses: azure/login@v1
        with:
          creds: '${{ secrets.azure_credentials }}'
          enable-AzPSSession: true

      - name: Login to Azure Container Registry
        uses: Azure/docker-login@v1
        with:
          login-server: ${{ inputs.container_registry }}
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      
      - name: Set target AKS cluster
        uses: Azure/aks-set-context@v1
        with:
          creds: '${{ secrets.azure_credentials }}'
          cluster-name: ${{ inputs.aks_cluster_name }}
          resource-group: ${{ inputs.aks_cluster_rg }}

      - name: Switch to Deployment Namespace
        run: kubectl config set-context --current --namespace=${{ inputs.environment }}
      
      - name: Apply ConfigMap
        if: ${{ steps.getenvs.outputs.CONFIGMAP != null }}
        uses: swdotcom/update-and-apply-kubernetes-configs@v1
        with:
          k8-config-file-paths: deployments/k8s/config-${{ inputs.environment }}.yaml
      
      - name: Add GitHub secrets to k8s
        if: ${{ steps.getenvs.outputs.CONFIGSECRET != null }}
        uses: Azure/k8s-create-secret@v1
        with:
          namespace: ${{ inputs.environment }}
          secret-type: 'generic'
          arguments: '--from-literal=${{ inputs.secret_key1 }}=${{ secrets.secret_value1 }}
                      --from-literal=${{ inputs.secret_key2 }}=${{ secrets.secret_value2 }}
                      --from-literal=${{ inputs.secret_key3 }}=${{ secrets.secret_value3 }}
                      --from-literal=${{ inputs.secret_key4 }}=${{ secrets.secret_value4 }}
                      --from-literal=${{ inputs.secret_key5 }}=${{ secrets.secret_value5 }}
                      --from-literal=${{ inputs.secret_key6 }}=${{ secrets.secret_value6 }}
                      --from-literal=${{ inputs.secret_key7 }}=${{ secrets.secret_value7 }}
                      --from-literal=${{ inputs.secret_key8 }}=${{ secrets.secret_value8 }}'
          secret-name: ${{ steps.getenvs.outputs.CONFIGSECRET }}

      - name: Create or Update Public DNS Record
        uses: azure/powershell@v1
        with:
          inlineScript: |
            $NewRecords = New-AzDnsRecordConfig -Cname ${{ inputs.aks_ingress_fqdn }};
            New-AzDnsRecordSet -Name "${{ steps.getenvs.outputs.HOSTNAME  }}" -RecordType CNAME -ZoneName ${{ steps.getenvs.outputs.DOMAINNAME  }} -ResourceGroupName ${{ inputs.dns_rg }} -Ttl 3600 -DnsRecords $NewRecords -Overwrite;
          azPSVersion: '3.1.0'

      - name: Create k8s Image Pull Secret
        uses: Azure/k8s-create-secret@v1
        with:
          container-registry-url: ${{ inputs.container_registry }}
          container-registry-username: ${{ secrets.registry_username }}
          container-registry-password: ${{ secrets.registry_password }}
          secret-name: ${{ steps.getenvs.outputs.IMAGEPULLSECRET }}

      - name: Build & Push Docker Image
        run: |
          docker build ${{ inputs.dockerfile_path }}  -t ${{ inputs.container_registry }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
          docker push ${{ inputs.container_registry }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}

      
      - name: Create valid release-name
        id: generate-release-name
        run: |
          release=${{ inputs.docker_image_name }}-${{ inputs.docker_image_tag }}
          release=${release::53}
          release=$(echo ${release//[!0-9a-zA-Z]/-} | tr '[:upper:]' '[:lower:]' | sed -e 's/^-/z/' -e 's/-$/z/')
          echo ::set-output name=result::$release

      - name: Bake Helm templates
        uses: azure/k8s-bake@v1
        with:
          renderEngine: 'helm'
          helmChart: ${{ inputs.charts_path }}
          releaseName: ${{steps.generate-release-name.outputs.result}}
          helm-version: 'latest'
          overrides: |
            image.repository:${{ inputs.container_registry }}/${{ inputs.docker_image_name }}
            image.tag:${{ inputs.docker_image_tag }}
            ingress.host:${{ steps.getenvs.outputs.APPINGRESS }}
            autoscaling.maxReplicas:${{ inputs.application_maximum_replicas }}
        id: bake

      - name: Deploy to Azure
        uses: Azure/k8s-deploy@v1
        with:
          namespace: ${{ inputs.environment }}
          manifests: ${{ steps.bake.outputs.manifestsBundle }}
          images: |
            ${{ inputs.container_registry }}/${{ inputs.docker_image_name }}:${{ inputs.docker_image_tag }}
          imagepullsecrets: |
            ${{ steps.getenvs.outputs.IMAGEPULLSECRET }}
    outputs:
      environment: ${{ inputs.environment }}
      hostName: ${{ steps.getenvs.outputs.HOSTNAME }}
      domainName: ${{ steps.getenvs.outputs.DOMAINNAME }}
      fqdn: ${{ steps.getenvs.outputs.INGRESS }}
      aks_ingress_fqdn: ${{ inputs.aks_ingress_fqdn }}

