name: Build and Deploy B2C auth application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Deploy Environment.  This is used to pull in and set the github environment. Can be development, staging, or production."
      environmentKeyVault:
        required: true
        type: string
        description: "Azure Key vault Name."
      azureB2CProductName:
        required: true
        type: string
        description: "Name of the B2C product."
      azureB2CDomain:
        required: true
        type: string
        description: "Domain name of the B2C tenant."
      azureB2CProductUrl:
        required: false
        type: string
        description: "URL of the B2C Product."
    secrets:
      azureCredentials:
        required: true
      storageAccountKey:
        required: true
      azureB2CClientId:
        required: true
      azureB2CClientSecret:
        required: true

jobs:
  vars:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          if [[ "${{ inputs.environment }}" == "production" ]] ; then
              echo "url=amub2c.b2clogin.com" >> $GITHUB_ENV
          else
              echo "url=${{ inputs.environment }}amub2c.b2clogin.com" >> $GITHUB_ENV
          fi
          echo "azureB2CClientId=${{ secrets.azureB2CClientId }}" >> $GITHUB_ENV
    outputs:
      url: ${{ env.url }}
      azureB2CClientId: ${{ env.azureB2CClientId }}

  build:
    name: Build B2C Application
    needs: [vars]
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.azureB2CProductName }}-${{ inputs.environment }}
      url: "https://${{ needs.vars.outputs.url }}/${{ inputs.azureB2CDomain }}/b2c_1a_gc_signinsignout_policies/oauth2/v2.0/authorize?client_id=${{ needs.vars.outputs.azureB2CClientId }}&scope=https%3A%2F%2F${{ inputs.azureB2CDomain }}%2Fapi%2Fdemo.read%20https%3A%2F%2F${{ inputs.azureB2CDomain }}%2Fapi%2Fdemo.write%20https%3A%2F%2F${{ inputs.azureB2CDomain }}%2Fapi%2Fuser_impersonation%20offline_access%20openid&response_type=code&redirect_uri=https%3A%2F%2F${{ inputs.azureB2CProductUrl }}%2Fapi%2Fauth%2Fcallback%2Fazureb2c"
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login via Az module
        uses: azure/login@v1.4.7
        with:
          creds: ${{ secrets.azureCredentials }}
          enable-AzPSSession: true

      - name: Generate .env file from Azure Key Vaults
        uses: Andrews-McMeel-Universal/get-envs@v1
        with:
          azurecredentials: ${{ secrets.azureCredentials }}
          environment: ${{ inputs.environment }}
          environmentKeyVault: ${{ inputs.environmentKeyVault }}

      - name: Get Fresh Packages
        shell: pwsh
        run: |
          yarn install

      - name: Build Policies
        shell: pwsh
        run: |
          $Environment = "${{ inputs.environment }}"
          $ProductName = "${{ inputs.azureB2CProductName }}".Replace("-","").Replace("the","")
          yarn config set product $ProductName
          yarn config set environment $Environment
          yarn build

      - name: "Upload TrustFrameworkBase Policy"
        uses: azure-ad-b2c/deploy-trustframework-policy@v5.3
        with:
          folder: "./dist/${{ inputs.azureB2CProductName }}/custom-policies"
          files: "B2C_1A_TPS_SIGNINSIGNOUT_BASE.xml,B2C_1A_TPS_SIGNINSIGNOUT_EXTENSIONS.xml,B2C_1A_TPS_SIGNINSIGNOUT_POLICIES.xml,B2C_1A_TPS_IMPERSONATION.xml"
          tenant: ${{ inputs.azureB2CDomain }}
          clientId: ${{ secrets.azureB2CClientId }}
          clientSecret: ${{ secrets.azureB2CClientSecret }}

      - name: Upload Auth Assets
        uses: azure/powershell@v1.2.0
        with:
          inlineScript: |
            $BasePath = Get-Location
            $DistPath = Join-Path $BasePath "dist"
            ./deployments/scripts/Deploy-B2C_Auth.ps1 -StorageAccountName "amuauthassets" -StorageAccountKey "${{ secrets.storageAccountKey }}" -ContainerName "${{ inputs.environment }}-assets" -DistPath $DistPath -ProductPath "${{ inputs.azureB2CProductName }}"
          azPSVersion: "latest"

      - name: Purge CDN Cache
        run: |
          az cdn endpoint purge --resource-group 'Site_Assets' --profile-name 'amuauthassets' --name 'amuauthassets' --content-paths '/*'
