name: Build and Deploy B2C auth application

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Deploy Environment.  This is used to pull in and set the github environment. Can be development, staging, or production."
      environmentKeyVault:
        required: false
        type: string
        description: "AKS Key vault."
      azureB2CDomain:
        required: true
        type: string
        description: "Domain name of the B2C tenant."
      azureB2CTenantId:
        required: true
        type: string
        description: "Tenant Id for the B2C tenant."
      azureB2CProductUrl:
        required: false
        type: string
        description: "URL of the B2C Product."
    secrets:
      azureCredentials:
        required: true
      storageAccountKey:
        required: true
      azureB2CClientId:
        required: true
      azureB2CClientSecret:
        required: true

jobs:
  vars:
    name: Set Environment Variables
    runs-on: ubuntu-latest
    steps:
      - name: Set environment variables
        run: |
          if [[ "${{ inputs.environment }}" == "production" ]] ; then
              echo "url=amub2c.b2clogin.com" >> $GITHUB_ENV
          else
              echo "url=${{ inputs.environment }}amub2c.b2clogin.com" >> $GITHUB_ENV
          fi
          echo "azureB2CClientId=${{ secrets.azureB2CClientId }}" >> $GITHUB_ENV
    outputs:
      url: ${{ env.url }}
      azureB2CClientId: ${{ env.azureB2CClientId }}

  build:
    name: Build B2C Application
    needs: [vars]
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}
      url: "https://${{ needs.vars.outputs.url }}/${{ inputs.azureB2CDomain }}/b2c_1a_gc_signinsignout_policies/oauth2/v2.0/authorize?client_id=${{ needs.vars.outputs.azureB2CClientId }}&scope=https%3A%2F%2F${{ inputs.azureB2CDomain }}%2Fapi%2Fdemo.read%20https%3A%2F%2F${{ inputs.azureB2CDomain }}%2Fapi%2Fdemo.write%20https%3A%2F%2F${{ inputs.azureB2CDomain }}%2Fapi%2Fuser_impersonation%20offline_access%20openid&response_type=code&redirect_uri=https%3A%2F%2F${{ inputs.azureB2CProductUrl }}%2Fapi%2Fauth%2Fcallback%2Fazureb2c"
    continue-on-error: false
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Generate .env file from Azure Key Vaults
        uses: Andrews-McMeel-Universal/get-envs@v1
        with:
          azurecredentials: ${{ secrets.azureCredentials }}
          environment: ${{ inputs.environment }}
          environmentKeyVault: ${{ inputs.environmentKeyVault }}

      - name: Get Fresh Packages
        run: |
          yarn install

      - name: Build Policies
        run: |
          yarn build

      - name: Upload TrustFrameworkBase Policy
        uses: Andrews-McMeel-Universal/deploy-trustframework-policy@v6
        with:
          folder: "./dist/custom-policies/"
          files: "B2C_1A_${{ env.AZURE_B2C_PRODUCT_ID }}_SIGNINSIGNOUT_BASE.xml,B2C_1A_${{ env.AZURE_B2C_PRODUCT_ID }}_SIGNINSIGNOUT_EXTENSIONS.xml,B2C_1A_${{ env.AZURE_B2C_PRODUCT_ID }}_SIGNINSIGNOUT_POLICIES.xml,B2C_1A_${{ env.AZURE_B2C_PRODUCT_ID }}_IMPERSONATION.xml,B2C_1A_${{ env.AZURE_B2C_PRODUCT_ID }}_SIGNINSIGNOUT_IMPERSONATION.xml"
          tenantDomain: ${{ env.AZURE_B2C_DOMAIN }}
          tenantId: ${{ env.AZURE_B2C_TENANT_ID }}
          clientId: ${{ env.AZURE_B2C_CLIENT_ID }}
          clientSecret: ${{ env.AZURE_B2C_CLIENT_SECRET }}

      - name: Upload Auth Assets
        uses: azure/powershell@v1
        with:
          inlineScript: |
            if ("${{ inputs.environment }}" -match "production") {
                $ContainerName = "assets"
            }
            else {
                $ContainerName = "${{ inputs.environment }}-assets"
            }
            $DistPath = Join-Path (Get-Location) "dist"
            ./deployments/scripts/Deploy-B2C-Auth.ps1 -StorageAccountName "amuauthassets" -StorageAccountKey "${{ secrets.storageAccountKey }}" -ContainerName $ContainerName -DistPath $DistPath
          azPSVersion: "latest"
