name: Bump App Version

on:
  workflow_call:
    inputs:
      releaseType:
        required: false
        type: string
        description: Type of release
      version:
        required: false
        type: string
        description: The version to bump to. If not provided, the next version will be calculated based on the latest release
    secrets:
      PAT_ACTION_CI:
        required: false

jobs:
  bump-version:
    name: Bump ${{ inputs.version || inputs.releaseType }} Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0

      - name: Get latest release
        if: ${{ ! inputs.version }}
        run: |
          LATEST_RELEASE=$(curl -sL "${{ github.api_url }}/repos/${{ github.repository }}/releases/latest" -H "Authorization: token ${{ github.token }}" | grep "tag_name" | awk -F ':' '{print $2}' | tr -d '", ')
          echo "latestRelease=${LATEST_RELEASE}" >> $GITHUB_ENV

      - name: Set app variables
        shell: pwsh
        env:
          chartsPath: ${{ env.chartsPath }}
        run: |
          # Set app variables

          if (Test-Path -Path "./deployments/production-charts") {
              echo "chartsPath=./deployments/production-charts"
              echo "chartsPath=./deployments/production-charts" >> $env:GITHUB_ENV
          }
          else {
              echo "chartsPath=./deployments/charts"
              echo "chartsPath=./deployments/charts" >> $env:GITHUB_ENV
          }
          
          # Load Helm chart values
          $basePath = Get-Location
          $chartYamlPath = Join-Path $basePath $env:chartsPath "Chart.yaml"
          $chartConfig = Get-Content $chartYamlPath | ConvertFrom-Yaml

          # Set app version
          $appVersion = $chartConfig.appVersion
          Write-Output "appVersion=$appVersion"
          Write-Output "appVersion=$appVersion" >> $env:GITHUB_ENV

          # Check if package.json exists
          if (Test-Path -Path "./package.json") {
              echo "packageJsonExists=true"
              echo "packageJsonExists=true" >> $env:GITHUB_ENV
          }

      - name: Get package.json version
        if: ${{ env.packageJsonExists == 'true' && ! inputs.version }}
        run: |
          PACKAGE_VERSION=$(find . -name 'package.json' -d 1 -exec grep -h 'version' {} + | awk -F ':' '{print $2}' | tr -d '", ')
          echo "packageVersion=${PACKAGE_VERSION}" >> $GITHUB_ENV

      - name: Gets next semantic release
        if: ${{ ! inputs.version }}
        shell: pwsh
        env:
          releaseType: ${{ inputs.releaseType }}
        run: |
          [Version]$a = "${{ env.packageVersion || '0.0.0' }}"
          [Version]$b = "${{ env.appVersion || '0.0.0' }}"
          [Version]$c = "${{ env.latestRelease || '0.0.0' }}"

          $versions = [array]($a,$b,$c)
          $v = [version]($versions | Sort-Object -Descending | Select-Object -First 1)

          if ( "$env:releaseType" -match "major") {
            $release = [version]::New($v.Major+1,0,0)
          }
          elseif ( "$env:releaseType" -match "minor" ) {
            $release = [version]::New($v.Major,$v.Minor+1,0)
          }
          elseif ( "$env:releaseType" -match "patch" ) {
            $release = [version]::New($v.Major,$v.Minor,$v.Build+1)
          }

          echo "release=$release" >> $env:GITHUB_ENV
          echo "Bumping version to $release"

      - name: Update versions numbers in files
        run: |
          find . -iname "package.json" -not -path "./node_modules/*" -exec sed -i -E 's|(^.*"version": ").*(".*$)|\1${{ inputs.version || env.release }}\2|' {} \;
          find . -iname "Chart.yaml" -exec sed -i -E 's|(^appVersion: ).*($)|\1${{ inputs.version || env.release }}\2|' {} \;

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1v8
        with:
          commit-message: "⬆️ Version bump: ${{ inputs.version || env.release }}"
          branch: maintenance/bump-version/${{ inputs.version || env.release }}
          committer: AMU Automations <amu_deploy@amuniversal.com>
          delete-branch: true
          title: "⬆️ Version bump: ${{ inputs.version || env.release }}"
          body: |
            Updating version to ${{ inputs.version || env.release }} in:
            - `**/Charts.yaml`
            - `**/package.json`
          labels: |
            ${{ inputs.releaseType }}

      - name: Auto Approve Version Update PR
        uses: hmarr/auto-approve-action@f0939ea97e9205ef24d872e76833fa908a770363
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          github-token: ${{ secrets.PAT_ACTION_CI }}
