name: Bump App Version

on:
  workflow_call:
    inputs:
      releaseType:
        required: false
        type: string
        description: Type of release
      environmentCharts:
        required: false
        type: string
        description: Set to true if the repository has separate Helm chart directories for each environment
        default: 'false'
      version:
        required: false
        type: string
        description: The version to bump to. If not provided, the next version will be calculated based on the latest release
      updateAction:
        required: false
        type: string
        description: The action to perform. Default is create-pr
        default: 'create-pr'
    secrets:
      PAT_ACTION_CI:
        required: false

jobs:
  bump-version:
    name: Bump Versions ${{ inputs.releaseType }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get latest release
        if: ${{ ! inputs.version }}
        id: latestrelease
        continue-on-error: true
        uses: thebritican/fetch-latest-release@v2.0.0

      - name: Get Chart.yaml appVersion
        if: ${{ inputs.environmentCharts == 'false' && ! inputs.version }}
        id: chartyaml
        uses: rmeneely/get-yaml-value@v1
        with:
          infile: deployments/charts/Chart.yaml
          varlist: appVersion

      - name: Get Environment Chart.yaml appVersion
        if: ${{ inputs.environmentCharts == 'true' && ! inputs.version }}
        id: environmentchartyaml
        uses: rmeneely/get-yaml-value@v1
        with:
          infile: deployments/production-charts/Chart.yaml
          varlist: appVersion

      - name: Check if package.json exists
        id: packagejsonfile
        uses: andstor/file-existence-action@v2
        with:
          files: "package.json"

      - name: Get package.json version
        if: ${{ steps.packagejsonfile.outputs.files_exists == 'true' && ! inputs.version }}
        id: packagejson
        uses: notiz-dev/github-action-json-property@v0.2.0
        with:
          path: "package.json"
          prop_path: "version"

      - name: Gets next semantic release
        if: ${{ ! inputs.version }}
        shell: pwsh
        run: |
          [Version]$a = "${{ steps.packagejson.outputs.prop || '0.0.0' }}"
          [Version]$b = "${{ steps.environmentchartyaml.outputs.values || steps.chartyaml.outputs.values || '0.0.0' }}"
          [Version]$c = "${{ steps.latestrelease.outputs.tag_name || '0.0.0' }}"

          $versions = [array]($a,$b,$c)
          $v = [version]($versions | Sort-Object -Descending | Select-Object -First 1)

          if ( "${{ inputs.releaseType }}" -match "major") {
            $release = [version]::New($v.Major+1,0,0)
          }
          elseif ( "${{ inputs.releaseType }}" -match "minor" ) {
            $release = [version]::New($v.Major,$v.Minor+1,0)
          }
          elseif ( "${{ inputs.releaseType }}" -match "patch" ) {
            $release = [version]::New($v.Major,$v.Minor,$v.Build+1)
          }

          echo "release=$release" >> $env:GITHUB_ENV
          echo "Bumping version to $release"

      - name: Update version in package.json
        if: steps.packagejsonfile.outputs.files_exists == 'true'
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: '"version": .*'
          replace: '"version": "${{ inputs.version || env.release }}",'
          regex: true
          include: "**package.json"

      - name: Update version in Chart.yaml
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "appVersion: .*"
          replace: "appVersion: ${{ inputs.version || env.release }}"
          regex: true
          include: "**Chart.yaml"

      - name: Commit Changes
        if: ${{ inputs.updateAction == 'create-commit' }}
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: amutechtest
          commit_user_email: amu_deploy@amuniversal.com
          commit_message: ⬆️ Bump version

      - name: Check if branch exists
        if: ${{ inputs.updateAction == 'create-pr' }}
        id: branchexists
        run: |
          export BRANCHES=$(git branch -r)
          if echo "$BRANCHES" | grep -q "maintenance/bump-version/${{ inputs.version || env.release }}"; then
            echo "branch-exists=true" >> $GITHUB_OUTPUT
          fi

      - name: Create Pull Request
        if: ${{ inputs.updateAction == 'create-pr' && steps.branchexists.outputs.branch-exists != 'true' }}
        id: cpr
        uses: peter-evans/create-pull-request@v4
        with:
          commit-message: "⬆️ Version bump: ${{ inputs.version || env.release }}"
          branch: maintenance/bump-version/${{ inputs.version || env.release }}
          committer: AMU Automations <amu_deploy@amuniversal.com>
          delete-branch: true
          title: "⬆️ Version bump: ${{ inputs.version || env.release }}"
          body: |
            Updating version to ${{ inputs.version || env.release }} in:
            - `**/Charts.yaml`
            - `**/package.json`
          labels: |
            ${{ inputs.releaseType }}

      - name: Auto Approve Version Update PR
        if: ${{ inputs.updateAction == 'create-pr' }}
        uses: hmarr/auto-approve-action@v3
        with:
          pull-request-number: ${{ steps.cpr.outputs.pull-request-number }}
          github-token: ${{ secrets.PAT_ACTION_CI }}
