name: Do Not Merge

on:
  pull_request:

jobs:
  do-not-merge:
    name: Prevent Merging
    runs-on: ubuntu-latest
    steps:
      - name: Check for label
        if: ${{ contains(github.event.pull_request.labels.*.name, 'do not merge') }}
        run: |
          echo "Pull request is labeled as 'do not merge'"
          echo "This workflow fails so that the pull request cannot be merged"
          exit 1