name: Dotnet Application CI

on:
  workflow_call:
    inputs:
      environment:
        required: false
        type: string
        default: ${{ vars.APPLICATION_CI_ENVIRONMENT || 'development' }}
      projectName:
        required: false
        type: string
        description: Project Directory Name
        default: ${{ vars.DOTNET_PROJECT_NAME || ''}}
      DOTNET_VERSION:
        required: false
        type: string
        description: ".NET SDK Version"
        default: ${{ vars.DOTNET_VERSION }}
    secrets:
      AZURE_CREDENTIALS:
        required: true
      PAT_ACTION_CI:
        required: true

env:
  NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

jobs:
  build:
    name: Build App
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use .env cache action
        uses: Andrews-McMeel-Universal/get-envs@v1
        with:
          azurecredentials: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ inputs.environment }}

      - name: Retrieve .NET version
        id: dotnet-version
        run: |
          if [[ -z "${{ inputs.DOTNET_VERSION }}" ]]; then
            DOTNET_VERSION=$(find . -name '*.csproj' -exec grep -h '<TargetFramework>net' {} + | sed -E 's/.*<TargetFramework>net([0-9]+\.[0-9]+)<\/TargetFramework>.*/\1/' | sort -V | tail -n1)
            echo "DOTNET_VERSION=${DOTNET_VERSION}" >> $GITHUB_OUTPUT
          else
            echo "DOTNET_VERSION=${{ inputs.DOTNET_VERSION }}" >> $GITHUB_OUTPUT
          fi

      - name: Setup application platform
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ steps.dotnet-version.outputs.DOTNET_VERSION }}

      - name: Add AMU GitHub Packages nuget source
        run: |
          dotnet nuget add source "https://nuget.pkg.github.com/andrews-mcmeel-universal/index.json" --name "AMU GitHub Packages" --username "amu_deploy@amuniversal.com" --password "${{ secrets.PAT_ACTION_CI }}" --store-password-in-clear-text

      # Installs dependencies if the cache was broken
      - name: Cache dependencies
        id: install-cache
        uses: actions/cache@v4
        with:
          path: |
            ${{ github.workspace }}/.nuget/packages
            **/project.assets.json
            **/obj/
          # Look to see if there is a cache hit for the corresponding requirements file
          key: install-${{ hashFiles('**/*.csproj','**/project.assets.json') }}

      - name: Install dependencies
        if: steps.install-cache.outputs.cache-hit != 'true'
        working-directory: ${{ inputs.projectName }}
        run: dotnet restore

      # Builds the app if the cache was broken
      - name: Build app
        working-directory: ${{ inputs.projectName }}
        run: dotnet build -c Release --no-restore

      - name: Run tests
        working-directory: ${{ inputs.projectName }}
        run: dotnet test --no-restore --verbosity normal
