name: Run Jira Linter

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  workflow_call:
    secrets:
      JIRA_TOKEN:
        required: true

jobs:
  jira-lint:
    name: Run Jira Lint
    runs-on: ubuntu-latest
    steps:
      - uses: jira-tools/action-jira-linter@v1.0.1
        name: Jira Lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://amuniversal.atlassian.net
          pr-threshold: 1000
          jira-user: amu_deploy@amuniversal.com
          validate-issue-status: true
          allowed-issue-statuses: |
            New
            Reopened
            To Do
            In Progress
            Peer Review
            In Staging / QA
            Ready For Staging
            In Development Env
            Approved
            Resolved
