name: Run Jira Linter

on:
  pull_request_target:
    types: [opened, synchronize, reopened]
  workflow_call:

jobs:
  jira-lint:
    name: Run Jira Lint
    runs-on: ubuntu-latest
    steps:
      - uses: btwrk/action-jira-linter@v1.0.1
        name: Jira Lint
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          jira-token: ${{ secrets.JIRA_TOKEN }}
          jira-base-url: https://amuniversal.atlassian.net
          skip-comments: true
          pr-threshold: 1000