name: Lint and Format Code

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [main]
  workflow_call:
    secrets:
      PAT_ACTION_CI:
        required: true
  workflow_dispatch:

jobs:
  lint:
    name: Run MegaLinter
    runs-on: ubuntu-latest
    steps:
      # Run the MegaLinter Github Action
      - name: MegaLinter
        id: ml
        # You can override MegaLinter flavor used to have faster performances
        # More info at https://megalinter.io/flavors/
        uses: oxsecurity/megalinter/flavors/cupcake@v6.20.1
        env:
          VALIDATE_ALL_CODEBASE: ${{ github.event_name == 'workflow_dispatch' }}
          GITHUB_TOKEN: ${{ secrets.PAT_ACTION_CI }}

      # Creates archive artifact of linting reports
      # Upload MegaLinter artifacts
      - name: Archive production artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: MegaLinter reports
          path: |
            megalinter-reports
            mega-linter.log
          retention-days: 7

      # Commit fixes back into the raised PR branch
      - name: Prepare Linting Fix Commit
        if: steps.ml.outputs.has_updated_sources == 1 && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main'
        run: sudo chown -Rc $UID .git/

      - name: Commit and Push Linting Fixes
        if: steps.ml.outputs.has_updated_sources == 1 && env.APPLY_FIXES_MODE == 'commit' && github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: amutechtest
          commit_user_email: amu_deploy@amuniversal.com
          commit_message: "[MegaLinter] Apply prettier changes"
