name: Next.js Application CI

on:
  workflow_call:
    secrets:
      AZURE_CREDENTIALS:
        required: true
      PAT_ACTION_CI:
        required: true

env:
  azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}

jobs:
  # Sets up dependencies and initial cache
  setup-and-build:
    name: Setup and Build Application
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Build Args Cache Action
        uses: ./.github/actions/use-build-args-cache

      - name: Next.js Install Cache Action
        uses: ./.github/actions/use-nextjs-install-cache

      - name: Next.js Build Cache Action
        uses: ./.github/actions/use-nextjs-build-cache

  # Reformats code
  lint-and-format:
    name: Lint and Format
    runs-on: ubuntu-latest
    needs: [setup-and-build]
    timeout-minutes: 5
    steps:
      # This uses the PAT_ACTION_CI token as the normal GITHUB_TOKEN
      # doesn't have the permissions to trigger additional workflows
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.PAT_ACTION_CI }}

      - name: Build Args Cache Action
        uses: ./.github/actions/use-build-args-cache

      - name: Next.js Install Cache Action
        uses: ./.github/actions/use-nextjs-install-cache

      - name: Next.js Build Cache Action
        uses: ./.github/actions/use-nextjs-build-cache

      - name: Lint javascript
        run: yarn lint:js

      - name: Lint scss
        run: yarn lint:styles

      # This step must be after other jobs or steps that might add or change files
      - name: Run formatter
        run: yarn format-all

      # With the correct PAT token permissions, this can trigger
      # another set of CI tests and workflows after it adds new commits.
      - name: Commit formatting changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: amutechtest
          commit_user_email: amu_deploy@amuniversal.com
          commit_message: Apply prettier changes

  # Run Jest Unit tests
  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: [setup-and-build,lint-and-format]
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Build Args Cache Action
        uses: ./.github/actions/use-build-args-cache

      - name: Next.js Install Cache Action
        uses: ./.github/actions/use-nextjs-install-cache

      - name: Next.js Build Cache Action
        uses: ./.github/actions/use-nextjs-build-cache

      - name: Run Jest tests
        run: yarn test:unit:ci

  # Runs Playwright integration tests
  integration-tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    # needs: [build, check-linters]
    needs: [setup-and-build,lint-and-format]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Build Args Cache Action
        uses: ./.github/actions/use-build-args-cache

      - name: Next.js Install Cache Action
        uses: ./.github/actions/use-nextjs-install-cache

      - name: Next.js Build Cache Action
        uses: ./.github/actions/use-nextjs-build-cache

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: yarn test:integration:ci

      - name: Upload Playwright Report Artifact
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  check-links:
    name: Check Application Links
    runs-on: ubuntu-latest
    needs: [setup-and-build,lint-and-format]
    timeout-minutes: 10
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Build Args Cache Action
        uses: ./.github/actions/use-build-args-cache

      - name: Next.js Install Cache Action
        uses: ./.github/actions/use-nextjs-install-cache

      - name: Next.js Build Cache Action
        uses: ./.github/actions/use-nextjs-build-cache

      - name: Run Broken Link Checker
        id: link-checker-report
        continue-on-error: true
        run: yarn postbuild && yarn test:links

      - name: Link Checker Results
        if: ${{ failure() }}
        run: echo "::warning ${{steps.link-checker-report.outputs.result}}"

  # Checks gzipped page sizes, uses caches from setup-and-build
  check-size:
    runs-on: ubuntu-latest
    name: Get File Sizes Limits
    needs: [setup-and-build,lint-and-format]
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - name: Build Args Cache Action
        uses: ./.github/actions/use-build-args-cache

      - name: Next.js Install Cache Action
        uses: ./.github/actions/use-nextjs-install-cache

      - name: Next.js Build Cache Action
        uses: ./.github/actions/use-nextjs-build-cache
      
      - name: Size Limit Action
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # The size-limit-action tries to run a 
          # redundant yarn build
          skip_step: build
