name: Add PR Labels

on:
  pull_request:
  workflow_call:
    secrets:
      PAT_ACTION_CI:
        required: true

jobs:
  # Automatically apply labels that match globs, defined in .github/labeler.yml
  # https://github.com/marketplace/actions/labeler
  triage-labels:
    name: Apply labels
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.PAT_ACTION_CI }}
          sync-labels: true

  # Prevent merging if certain labels exist
  # https://github.com/marketplace/actions/require-labels
  check-required-labels:
    name: Check for "do not merge" label
    runs-on: ubuntu-latest
    steps:
      - uses: mheap/github-action-required-labels@v3
        with:
          mode: exactly
          count: 0
          labels: "do not merge"
