name: 📄 Create Release Draft

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_call:
    secrets:
      PAT_ACTION_CI:
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  update-release-draft:
    name: Update Release Draft
    runs-on: ubuntu-latest
    steps:
      - name: Draft Release Notes
        uses: release-drafter/release-drafter@v6.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ACTION_CI }}