name: Simple Linter and Formatter

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_call:
    inputs:
      runPrettier:
        default: true
        type: boolean
      prettierPlugins:
        description: Install Prettier plugins, i.e. '@prettier/plugin-php @prettier/plugin-other'
        type: string
    secrets:
      PAT_ACTION_CI:
        required: true

jobs:
  prettier:
    name: Prettier Check
    if: ${{ inputs.runPrettier || github.event_name != 'workflow_call' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT_ACTION_CI }}

      - name: Run yarn install
        if: ${{ inputs.prettierPlugins }}
        run: yarn install

      - uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --write .
          prettier_plugins: ${{ inputs.prettierPlugins }}
          commit_message: Apply prettier changes
          github_token: ${{ secrets.PAT_ACTION_CI }}

  lint-workflows:
    name: Workflow linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)
        shell: bash

      - name: Lint workflow files
        run: ${{ steps.get_actionlint.outputs.executable }} -color -ignore "SC2086" -ignore "SC2129"
        shell: bash
