name: Update Game Configs

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      checkoutRef:
        required: false
        type: string
        description: "The branch, tag, or SHA to checkout"
        default: ${{ github.ref }}
    secrets:
      AZURE_CREDENTIALS:
        required: true

jobs:
  update:
    name: Update Game Configs
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.checkoutRef }}

      - name: Generate .env file from Azure Key Vaults
        uses: Andrews-McMeel-Universal/get-envs@v1
        with:
          azurecredentials: ${{ secrets.AZURE_CREDENTIALS }}
          environment: ${{ inputs.environment }}

      - name: Update Game Configs
        shell: pwsh
        run: |
          ./deployments/scripts/Update-CloudGameConfigs.ps1 -DBConnectionString "${{ env.DB_CONNECTION_STRING }}" -StorageAccountKey "${{ env.STORAGE_ACCOUNT_KEY }}" -ContainerName "${{ env.STORAGE_ACCOUNT_CONTAINER }}" -UpdatedBy 'GitHub Actions'