name: WP Engine Deployment

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: "Deploy Environment. Can be development, staging, or production."
      WPE_ENV_NAME:
        type: string
        description: WordPress engine site environment name
        required: true
      SOURCE_PATH:
        type: string
        description: WordPress engine site source path
        required: true
      PUBLISH_PATH:
        type: string
        description: WordPress engine site destination path
        required: true
      checkoutRef:
        required: false
        type: string
        description: "The branch, tag, or SHA to checkout"
        default: ${{ github.ref }}
      deploymentWebhook:
        required: false
        type: string
        description: "The webhook URL for the deployment status"
        default: ${{ vars.MSTEAMS_DEPLOYMENT_WEBHOOK }}
    secrets:
      WPENGINE_ED25514:
        required: true

jobs:
  deploy:
    name: WP Engine Deployment
    runs-on: ubuntu-latest
    continue-on-error: false
    environment:
      name: ${{ inputs.environment }}
      url: https://${{ inputs.WPE_ENV_NAME }}.wpengine.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.checkoutRef }}

      - name: Deploy to WP Engine
        uses: wpengine/github-action-wpe-site-deploy@v3
        with:
          # Deploy vars
          WPE_SSHG_KEY_PRIVATE: ${{ secrets.WPENGINE_ED25514 }}
          WPE_ENV: ${{ inputs.WPE_ENV_NAME }}
          # Deploy Options
          SRC_PATH: ${{ inputs.SOURCE_PATH }}
          REMOTE_PATH: ${{ inputs.PUBLISH_PATH }}
          PHP_LINT: TRUE
          FLAGS: -azvr --inplace --delete --exclude=".*" --exclude-from=.deployignore
          #SCRIPT: "path/yourscript.sh"
          CACHE_CLEAR: TRUE

      - name: Send Failed Deployment report to Teams
        if: failure() && ${{ inputs.environment != 'development' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ inputs.deploymentWebhook }}
          notification-summary: "${{ github.event.release.tag_name != '' && format('{0} ', github.event.release.tag_name) || ' ' }}Failed ${{ inputs.environment }} Deployment"
          notification-color: 17a2b8
          timezone: America/Chicago
          verbose-logging: true

      - name: Send Succeeded Deployment report to Teams
        if: success() && ${{ inputs.environment != 'development' }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }} # this will use the runner's token.
          ms-teams-webhook-uri: ${{ inputs.deploymentWebhook }}
          notification-summary: "${{ github.event.release.tag_name != '' && format('{0} ', github.event.release.tag_name) || ' ' }}Successful ${{ inputs.environment }} Deployment"
          notification-color: 28a745
          timezone: America/Chicago
          verbose-logging: true
